version : '3.9'

services : 
  mariadb :
    image : mariadb
    container_name : mariadb
    volumes :
      - mariadb:/var/lib/mysql
    networks : 
      - inception
    build :
      - context : /requirements/mariadb
      - dockerfile : Dockerfile
    env_file : .env
    expose :
      - "3306"
    restart : on-failure

  wordpress :
    image : wordpress
    container_name : wordpress
    volumes :
      - wordpress:/var/www/wordpress
    networks :
      - inception
    build : 
      - context : /requirements/wordpress
      - dockerfile : Dockerfile
    env_file : .env
    ports : 
      - "443:443"
    restart : on-failure

  nginx :
    image : nginx
    container_name : nginx
    volumes :
      wordpress:/var/www/wordpress
    build :
      context : /requirements/nginx
      dockerfile : Dockerfile
    networks :
      - inception
    env_file : .env
    expose : 
      - "9000"

# volumes : 


  
  