version : '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env.test
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env.test
    expose:
      - "9000"

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env.test
    ports:
      - "443:443"


volumes : 
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/miroka/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/miroka/wordpress

networks:
  inception:
    driver: bridge
